name: Validate code quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - name: Verify working directory
        run: echo "Processing folder: ${{ matrix.folder }}"
      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: yarn
      - name: Format code
        working-directory: ${{ matrix.folder }}
        run: yarn format
      - name: Typecheck
        working-directory: ${{ matrix.folder }}
        run: yarn typecheck
      - name: Lint
        working-directory: ${{ matrix.folder }}
        run: yarn lint